import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Marlon Lavanda</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Page under construction
        </h1>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Github &rarr;</h2>
          </a>
          <a
            href="https://www.linkedin.com/in/marlon-lavanda/"
            className={styles.card}
          >
            <h2>Linkedin &rarr;</h2>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
          <span className={styles.logo}>
            © Marlon Lavanda 2022 | All rights reserved.
          </span>
      </footer>
    </div>
  )
}
